### ISSUE TITLE
problem?

### ISSUE THREAD

**Issue by rnrsr** [deostroll/generator-mono#1]
Hey i tried this out in npm, but something is not working correctly. I have other packages installed ok, and i get a positive confirmation when running `npm install -g generator-mono` but then it doesn't list it when i check installed packages. 

The only warnings i get during installation:

```
npm WARN enoent ENOENT: no such file or directory, open '/home/my_usr/package.json'
npm WARN mr_tea No description
npm WARN mr_tea No repository field.
npm WARN mr_tea No README data
npm WARN mr_tea No license field.

```

Just spent a fair bit of time checking things out, and i ended up here: [runkit.com/npm/generator-mono](https://runkit.com/npm/generator-mono)  (hit the "run" button to check the build) . Their site appears to have the same problem, or is this a coincidence? They say they should have it, but its the same problem i get.

**Comment by deostroll** [comment]
Hi.

Thanks for trying out... Can you give me a step-by-step reproduction of the
issue.

**Comment by deostroll** [comment]
Sorry, i got ur issue. What happens post that...are you able to work with
writing c# code?
